name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Build Spring application
        run: |
          ./mvnw package -DskipTests=true
        working-directory: .
        
      - name: Build Docker image
        run: |
          docker build -t kwojtowicz/url-shortener:latest --platform linux/amd64 .
          docker login -u kwojtowicz -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push kwojtowicz/url-shortener:latest
      
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull kwojtowicz/url-shortener:latest
            docker stop url-shortener-app-api || true
            docker rm url-shortener-app-api || true
            docker run -d -p 8080:8080 --name url-shortener-app-api kwojtowicz/url-shortener:latest
